name: AutoBroadcasts
main: AutoBroadcasts\Main
version: 1.0.0
api: 5.0.0
author: ZyberPE

permissions:
  autobroadcast.use:
    default: op

commands:
  broadcast:
    description: Broadcast a custom message
    usage: "/broadcast <message>"
    permission: autobroadcast.use
